env:
  browser: true
  es2021: true
  node: true
extends:
  - airbnb-typescript/base
  - plugin:import/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  project: ./tsconfig.json
  sourceType: module
settings:
  'import/resolver':
    typescript:
      project: '.'
plugins:
  - '@typescript-eslint'
  - prettier
rules:
  prettier/prettier: 'error'
  '@typescript-eslint/no-unused-vars':
    - 'error'
    - argsIgnorePattern: '^_'
