name: Publish

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: "~1.38"

      - name: Generate docs
        run: deno task doc

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs

      - name: Setup Node.js package
        run: |
            TAG_SHA=`git rev-list --tags --max-count=1`
            TAG=`git describe --tags $TAG_SHA`
            deno run -A ./scripts/build_npm.ts ${TAG#v}

      - uses: JS-DevTools/npm-publish@v3
        with:
            token: ${{ secrets.NPM_TOKEN }}
